proposal:
    pattern:  /
    defaults: { _controller: "TGCAdminBundle:Proposal:index" }

proposal_show:
    pattern:  /{id}/show
    defaults: { _controller: "TGCAdminBundle:Proposal:show" }

proposal_new:
    pattern:  /new
    defaults: { _controller: "TGCAdminBundle:Proposal:new" }

proposal_create:
    pattern:  /create
    defaults: { _controller: "TGCAdminBundle:Proposal:create" }
    requirements: { _method: post }

proposal_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TGCAdminBundle:Proposal:edit" }

proposal_update:
    pattern:  /{id}/update
    defaults: { _controller: "TGCAdminBundle:Proposal:update" }
    requirements: { _method: post|put }

proposal_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TGCAdminBundle:Proposal:delete" }
    requirements: { _method: post|delete }
