parameters:
#    tgc_admin.example.class: TGC\AdminBundle\Example

services:
#    tgc_admin.example:
#        class: %tgc_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    tgc_admin.registration.form.type:   
        class: TGC\AdminBundle\Form\Type\RegistrationFormType     
        arguments: [%fos_user.model.user.class%, %security.role_hierarchy.roles%]
        tags:       
            - { name: form.type, alias: tgc_admin_registration }

    tgc_admin.registration.upload:
        class: TGC\AdminBundle\EventListener\Registration\FileUploadListener
        arguments: [%cv_upload_dir%]
        tags:
            - { name: kernel.event_subscriber }